services:
  backend:
    build: .
    container_name: backend-haroldo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MICROSERVICE_IA_URL: ${MICROSERVICE_IA_URL}
      REDIS_BASE_URL: ${REDIS_BASE_URL}
      REDIS_BEARER_TOKEN: ${REDIS_BEARER_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    depends_on:
      - microservicio-ia
    networks:
      - haroldo-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  microservicio-ia:
    build: ../IA-Microservice
    container_name: microservicio-ia-haroldo
    ports:
      - "8081:8080"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - haroldo-network

  frontend:
    build: ../Frontend
    container_name: frontend-haroldo
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - haroldo-network

networks:
  haroldo-network:
    driver: bridge