spring.application.name=backend
spring.config.import=optional:dotenv:.env

# Database configuration >:3
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.umtlidnqgmsutxwmljyx
spring.datasource.password=OcNatCxX8XYrJNpy

spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Stuff
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect