spring.application.name=backend

microservice.ia.url=http://microservicio-ia:8081/ia/recomendacion

# Database configuration >:3
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.leak-detection-threshold=30000
spring.datasource.hikari.max-lifetime=1800000

#JPA Stuff
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect